In [82]:
import numpy as np
from tensorflow.keras.models import Sequential
import tensorflow as tf
from tensorflow.keras.layers import Dense
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [83]:
data = np.load(r"C:\Users\YUVRAJ\Videos\Quark-Gluon\root\data\X.npy")
y_train = np.load(r"C:\Users\YUVRAJ\Videos\Quark-Gluon\root\data\y.npy")

print(f"{data}\n{data.shape}")
print(f"{y_train}\n{y_train.shape}")

[[[ 2.68769142e-01  3.56903171e-01  4.74138734e+00  2.20000000e+01]
  [ 1.60076377e-01 -2.55609533e-01  4.55022910e+00  2.20000000e+01]
  [ 1.14868731e+00 -6.24380156e-02  4.50385377e+00 -2.11000000e+02]
  ...
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]]

 [[ 1.21266321e+00 -1.12853089e-01  3.04708757e+00 -2.11000000e+02]
  [ 2.40893976e-01 -1.67174886e-02  2.82705667e+00  2.20000000e+01]
  [ 1.02778452e-01 -8.58720522e-02  3.04180579e+00  2.20000000e+01]
  ...
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]]

 [[ 2.16829416e-01 -9.97057017e-01  5.32568913e-01  2.20000000e+01]
  [ 2.31359397e-01 -1.59192211e+00  2.02906587e-01  2.20000000e+01]
  [ 3.41572501e-01 -1.34588077e+

In [84]:
count_arr = []
std_dev = []
for i in range(0,4):
    count_arr.append(np.count_nonzero(data[:,:,i]))
sums_col = np.sum(data, axis=(0, 1))
padd = np.all(data==0, axis=-1)
for i in range(0,4):
    std_dev.append(np.std(data[:, :, i][~padd]))

data_norm = data.copy()
def Z_score(x, std_arr, padd, count, sums_col):
    x_train  = x.copy()   
    for i in range(0,4):
        mean = sums_col[i]/count[i]
        x_train[:,:,i][~padd] = (x[:,:,i][~padd] - mean)/(std_arr[i]);
    return x_train
x_train = Z_score(data,std_dev,padd,count_arr, sums_col)

cross_data = x_train.copy()


In [85]:
print(f"{x_train}\n{x_train.shape}")
print(f"{y_train}\n{y_train.shape}")

[[[-0.47854659  0.40339335  0.88090067  0.01229013]
  [-0.48294452 -0.29421479  0.77591575  0.01229013]
  [-0.44294329 -0.07420625  0.75044621 -0.4026803 ]
  ...
  [ 0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.        ]]

 [[-0.44035469 -0.13162542 -0.04961606 -0.4026803 ]
  [-0.47967447 -0.02213385 -0.17045798  0.01229013]
  [-0.48526291 -0.10089595 -0.05251684  0.01229013]
  ...
  [ 0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.        ]]

 [[-0.48064818 -1.13867042 -1.43060054  0.01229013]
  [-0.48006026 -1.8161792  -1.61165251  0.01229013]
  [-0.47560081 -1.53595572 -1.62428233  0.01229013]
  ...
  [ 0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.        ]]

 ...

 [[-0.46666948  1.48435447  0.7240

In [86]:
x_train = x_train.reshape(x_train.shape[0], -1)
model = tf.keras.Sequential([
    Dense(128,activation='relu',input_shape = (556,)),
    Dense(32,activation='relu'),
    Dense(25,activation='relu'),
    Dense(12,activation='relu'),
    Dense(1,activation='sigmoid',),
])
model.summary()

c:\Users\YUVRAJ\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_9"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_45 (Dense)                │ (None, 128)            │        71,296 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_46 (Dense)                │ (None, 32)             │         4,128 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_47 (Dense)                │ (None, 25)             │           825 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_48 (Dense)                │ (None, 12)             │           312 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_49 (Dense)                │ (None, 1)              │            13 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 76,574 (299.12 KB)

 Trainable params: 76,574 (299.12 KB)

 Non-trainable params: 0 (0.00 B)

In [90]:
model.compile(
    loss = tf.keras.losses.BinaryCrossentropy(),
    optimizer = tf.keras.optimizers.Adam(learning_rate = 0.001),
)
x_train, x_test, y_train, y_test = train_test_split(x_train, y_train, random_state=34, test_size=0.3)

model.fit(
    
    x_train,y_train,
    batch_size = 64,
    epochs = 50,
)

model.fit(x_train, y_train, validation_data=(x_test, y_test), epochs=20)


Epoch 1/50
536/536 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 0.0737
Epoch 2/50
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.0605
Epoch 3/50
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.0510
Epoch 4/50
536/536 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0563
Epoch 5/50
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.0521
Epoch 6/50
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.0571
Epoch 7/50
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.0452
Epoch 8/50
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.0423
Epoch 9/50
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.0438
Epoch 10/50
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.0388
Epoch 11/50
536/536 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0429
Epoch 12/50
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.0445
Epoch 13/50
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.0421
Epoch 14/50
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.0439
Epoch 15/50
536/536 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - lo

In [91]:
y_pred = model.predict(x_test)
for i in range(0, len(y_pred)):
    if(y_pred[i]>0.5):
        y_pred[i] = 1
    else:
        y_pred[i] = 0
accuracy = accuracy_score(y_test, y_pred)
matrix = confusion_matrix(y_test, y_pred)
Final = classification_report(y_test, y_pred)
print(f"Accuracy: {accuracy*100:.4f}%")
print(f"Confusion Matrix:\n{matrix}")
print(f"Classification Report:\n{Final}")

460/460 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step
Accuracy: 88.0884%
Confusion Matrix:
[[6378  863]
 [ 888 6571]]
Classification Report:
              precision    recall  f1-score   support

         0.0       0.88      0.88      0.88      7241
         1.0       0.88      0.88      0.88      7459

    accuracy                           0.88     14700
   macro avg       0.88      0.88      0.88     14700
weighted avg       0.88      0.88      0.88     14700

